### PR TITLE
Added Icon

### PR DESCRIPTION
**Pull request by nithincod**
hey @akhilender-bongirwar check it out
git6

### CODE REVIEW

**Review by akhilender-bongirwar — COMMENTED** [review]
@nithincod,  Why do you have 67 changed files when you just have added an icon for the app?

**Comment by nithincod** [comment]
hey i have deleted previous icons ,and added new in Android->res folder and same in ios folder &  for changes in App icon it needed podfile it added some json,when i pub get it.

**Comment by akhilender-bongirwar** [comment]
> hey i have deleted previous icons ,and added new in Android->res folder and same in ios folder & for changes in App icon it needed podfile it added some json,when i pub get it.

Good @nithincod, you actually need to update the PR description with such more meaningful context.

**Comment by Illuminati9** [comment]
@nithincod , did you used any dependency

**Comment by nithincod** [comment]
No @Illuminati9 no Dependency used.

**Comment by Charan0313** [comment]
ok then @nithincod , LGTM and mentioning again try to improve commit message and pr description from next time

**Pull request closed without merging**
