### PR TITLE
Chat bubble

### PR DESCRIPTION
**Pull request by nithincod**
hey @Illuminati9 check it out.I have added border radius, new fonds, padding, changed color, added letter spacing .

### CODE REVIEW

**Comment by Charan0313** [comment]
@nithincod  can you share the screen shot of it

**Comment by nithincod** [comment]
yes @Charan0313 here is my Changes for ChatBUBBLE designUI in Following ScrrenShot.

git9

**Comment by Charan0313** [comment]
@nithincod , try to follow the color theme of app so that looks more good

**Comment by nithincod** [comment]
hey @Charan0313 here are your required changes.

Screenshot 2024-03-16 at 20 07 43

**Comment by Charan0313** [comment]
@nithincod , LGTM

**Pull request closed without merging**
